eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
server:
  port: 9090
spring:
  application:
    name: zuul-gateway
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  routes:
  
    subscription-service:
      path: /subscriptions/**
      serviceId: subscription
   # stripPrefix: false
    
    book-service:
        path: /books/**
        serviceId: books
     #   stripPrefix: false
    
    
    
    
